-- Founder bug numbers: BUG-0000 to BUG-0009 are reserved and assigned by hand.
-- Everyone else gets a number automatically, starting at BUG-0010.

-- allow a manual value (members still cannot write this column: no column grant)
alter table public.bugs alter column bug_number set generated by default;
alter table public.bugs add constraint bugs_bug_number_nonneg check (bug_number >= 0);

-- automatic numbering continues from 10
alter table public.bugs alter column bug_number restart with 10;

-- Give a member's bug a founder number (0 to 9). Run in the SQL editor:
--   select assign_founder_number('someone@example.com', 0);
create or replace function public.assign_founder_number(member_email text, num integer)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid;
begin
  if session_user = 'authenticator' and not public.is_admin() then
    raise exception 'admins only';
  end if;
  if num is null or num < 0 or num > 9 then
    raise exception 'founder numbers are 0 to 9';
  end if;
  select u.id into uid from auth.users u where lower(u.email) = lower(trim(member_email));
  if uid is null then
    raise exception 'no member with that email';
  end if;
  if exists (select 1 from public.bugs b where b.bug_number = num and b.user_id <> uid) then
    raise exception 'number % is already taken', num;
  end if;
  update public.bugs set bug_number = num where user_id = uid;
  if not found then
    raise exception 'that member has not saved a bug yet';
  end if;
  return num;
end;
$$;

revoke all on function public.assign_founder_number(text, integer) from public, anon;
grant execute on function public.assign_founder_number(text, integer) to authenticated;
